language: python
notifications:
  email: false
before_install:
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install lxml
branches:
  only:
    - master
